# Generated by Django 3.1.3 on 2020-11-16 15:32

import cloudinary.models
import datetime
from django.db import migrations
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20201113_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_image',
            field=cloudinary.models.CloudinaryField(default=datetime.datetime(2020, 11, 16, 15, 32, 17, 197425, tzinfo=utc), max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
